name: first github workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: | 
        echo "HELLO WORLD!!!"
        echo "Hello there again!!"
      - name: print bye world
        run: echo "BYE WORLD!!!"
