name: second-workflow
on: [push , workflow_dispatch]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: printing world name
        run: echo "hello world"
      - name: checkout
        uses: actions/checkout@v3
  deploying:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: echo "deploying"
